# Generated by Django 3.2 on 2022-08-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='title_id',
            field=models.CharField(default='gg', max_length=100, verbose_name='Уникальный идентификатор'),
            preserve_default=False,
        ),
    ]
