# Generated by Django 4.1 on 2022-08-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_alter_image_image_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["image_id"]},
        ),
        migrations.AlterModelOptions(
            name="place",
            options={"ordering": ["latitude"]},
        ),
        migrations.AlterField(
            model_name="image",
            name="image_id",
            field=models.IntegerField(default=0, verbose_name="Позиция"),
        ),
    ]
