# Generated by Django 4.1 on 2022-08-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0005_alter_image_options_alter_place_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={"ordering": ["title"]},
        ),
    ]
