# Generated by Django 4.1 on 2022-08-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0006_alter_place_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_id",
            field=models.IntegerField(db_index=True, default=0, verbose_name="Позиция"),
        ),
    ]
