# Generated by Django 4.1 on 2022-08-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0007_alter_image_image_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={},
        ),
    ]
