# Generated by Django 3.1.2 on 2022-08-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20220822_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position_id']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_id',
            new_name='position_id',
        ),
    ]
