# Generated by Django 3.1.2 on 2022-08-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20220822_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position_id',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
