# Generated by Django 4.1 on 2022-08-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0016_auto_20220825_2023"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
